# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

sleeping = Category.create(name: 'Sleeping')
bathroom = Category.create(name: 'Bathroom')
kitchen = Category.create(name: 'Kitchen')
warm_clothes = Category.create(name: 'Warm Clothes')
clothes = Category.create(name: 'Clothes')
other_gear = Category.create(name: 'Other Gear')
food_sugestions = Category.create(name: 'Food Sugestions')
basecamp = Category.create(name: 'Base Camp')
beverages = Category.create(name: 'Beverages')


Item.create(name: "Tent", packed: true, category: sleeping)
Item.create(name: "Sleeping Bags", packed: true, category: sleeping)
Item.create(name: "Hide a Mats", category: sleeping)
Item.create(name: "Bedding", packed: true, category: sleeping)
Item.create(name: "Blankets", packed: true, category: sleeping)
Item.create(name: "Pillows", category: sleeping)
Item.create(name: "Hammock", category: sleeping)
Item.create(name: "Cots", category: sleeping)

Item.create(name: "Wipes", packed: true, category: bathroom)
Item.create(name: "Towels", packed: true, category: bathroom)
Item.create(name: "Soap", category: bathroom)
Item.create(name: "Shampoo", category: bathroom)
Item.create(name: "Mirror", category: bathroom)
Item.create(name: "Nail clipper", category: bathroom)
Item.create(name: "First aid kit", category: bathroom)

Item.create(name: "Lighter", packed: true, category: kitchen)
Item.create(name: "Kitchen supplies", packed: true, category: kitchen)
Item.create(name: "Coffee", packed: true, category: kitchen)
Item.create(name: "Coffee maker", packed: true, category: kitchen)
Item.create(name: "Condiments", category: kitchen)
Item.create(name: "Plates", category: kitchen)
Item.create(name: "Paper Towels", category: kitchen)
Item.create(name: "Utensils", category: kitchen)
Item.create(name: "Flipper", category: kitchen)
Item.create(name: "Grill Gear", category: kitchen)
Item.create(name: "Knife", category: kitchen)
Item.create(name: "Cutting Board", category: kitchen)
Item.create(name: "Cups", category: kitchen)
Item.create(name: "Grill & Gas", category: kitchen)
Item.create(name: "Garbage Bags", category: kitchen)

Item.create(name: "Puffy jackets", packed: true, category: warm_clothes)
Item.create(name: "Hats", packed: true, category: warm_clothes)
Item.create(name: "Gloves", packed: true, category: warm_clothes)

Item.create(name: "Socks", packed: true, category: clothes)
Item.create(name: "Underwear", packed: true, category: clothes)
Item.create(name: "Pjs", category: clothes)
Item.create(name: "Swimsuit", category: clothes)
Item.create(name: "Sunglasses", category: clothes)

Item.create(name: "Tools", packed: true, category: other_gear)
Item.create(name: "Axe", packed: true, category: other_gear)
Item.create(name: "Bug spray", packed: true, category: other_gear)
Item.create(name: "Sunscreen", packed: true, category: other_gear)
Item.create(name: "Jawbone", category: other_gear)
Item.create(name: "Lantern", category: other_gear)
Item.create(name: "Flashlight", category: other_gear)
Item.create(name: "Grill basket", category: other_gear)
Item.create(name: "Bungee cords", category: other_gear)
Item.create(name: "Converter", category: other_gear)
Item.create(name: "Camping chairs", category: other_gear)

Item.create(name: "Dish soap and sponge", packed: true, category: basecamp)
Item.create(name: "Tablecloth", packed: true, category: basecamp)
Item.create(name: "Foldable table", category: basecamp)

Item.create(name: "Eggs", category: food_sugestions)
Item.create(name: "Pickles", category: food_sugestions)
Item.create(name: "Cucumbers", category: food_sugestions)
Item.create(name: "Tomatoes", category: food_sugestions)
Item.create(name: "Veggies", category: food_sugestions)
Item.create(name: "Bacon", category: food_sugestions)
Item.create(name: "Tuna Salad", category: food_sugestions)
Item.create(name: "Naan", category: food_sugestions)
Item.create(name: "Hummus", category: food_sugestions)

Item.create(name: "Drinking Water", packed: true, category: beverages)
Item.create(name: "Beer", category: beverages)
Item.create(name: "Bourbon", category: beverages)
Item.create(name: "Mixers", category: beverages)